config/routes.rb
Rails.application.routes.draw do
 
  resources :users 
  resources :recipes do
  resources :reviews, only: [:create, :update]
end

  
  
  root 'welcome#home'
  get "/auth/google_oauth2/callback", to: "sessions#google_omniauth"
  get "/login", to: 'sessions#login', as: 'login'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#logout', as: 'logout'
  get '/home', to: 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, :description, :ingredients, :minutes, presence: true
    validates :minutes, numericality: { greatern_than: 0, less_than_equal_to: 200 }
    validates :description, length: { minimum: 5 }
    has_many :reviews
    has_many :users, through: :reviews
    validate :no_biryani
    scope :search, -> (name){ where("name LIKE ?", "%#{name}%")}
    scope :alphabetical, -> {order(:name)}
    scope :by_number_of_reviews, -> {
    left_joins(:reviews)
    .select("recipes.*, count(reviews.id) AS reviews_count")
    .group("recipes.id")
    .order("reviews_count DESC")
   }
     scope :average_review, -> {
    left_joins(:reviews)
    .select("recipes.*, avg(reviews.rating) AS average_review")
    .group("recipes.id")
    .order("average_review DESC")
   }

   def self.select_sort(sort)
    case sort
    when "alphabetical"
      alphabetical
    when "number_reviews"
      by_number_of_reviews
    when "average_review"
      average_review
    else
      all
    end
  end


    def average_review
        reviews.average(:rating).to_i
    end
   

    private

    def no_biryani
        if self.name.include?("biryani")
            self.errors.add(:name, "BIRYANI is not available")
        end
    end

    


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :rating, numericality: {greater_than: 0, less_than_or_equal_to: 5}
  validates :content, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, :email, uniqueness: true
    validates :username, :email, presence: true
    validates :zipcode, numericality: {greater_than_or_equal_to: 10001, less_than_or_equal_to: 99999}
   has_many :reviews
   has_many :recipes, through: :reviews
    has_secure_password
    
    
    
    validate :password_requirements_are_met

   def self.find_or_create_from_google(user_info)
        find_or_create_by(email: user_info[:email]) do |user|
            user.username = user_info[:name]
            user.password = SecureRandom.hex
        end
    end

    private 

    def password_requirements_are_met
        rules = {
          " must contain at least one lowercase letter"  => /[a-z]+/,
          " must contain at least one uppercase letter"  => /[A-Z]+/,
          " must contain at least one digit"             => /\d+/,
          " must contain at least one special character" => /[^A-Za-z0-9]+/
        }
      
        rules.each do |message, regex|
          errors.add( :password, message ) unless password.match( regex )
        end
      end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?
    before_action :redirect_if_not_logged_in

    


    def logged_in?
        !!session[:user_id]
      end

    def current_user
      logged_in? && User.find(session[:user_id])
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !current_user
      end
        

      
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :set_recipe, only: [:show, :edit, :update, :destroy]


    def index
        @recipes = Recipe.search(params[:search]).select_sort(params[:sort])
       
    end

    def new
     @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.create(recipe_params)
        if @recipe.save
           redirect_to recipes_path
        else
            render :new
        end
    
    end

    def show
        @review = Review.find_or_initialize_by(user: current_user, recipe: @recipe)
    end

    def edit
    end

    def update
        if @recipe.update(recipe_params)  
         redirect_to @recipe
         else
            render :edit
        end
        
    end

        def destroy
           @recipe.destroy
           redirect_to recipes_path
        end

    private

    def set_recipe
        @recipe = Recipe.find(params[:id])
    end


    def recipe_params
        params.require(:recipe).permit(:name, :ingredients, :description, :minutes, :image_url, :search, :sort)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_recipe
  before_action :set_review, only: [:create, :update]



    def create
    
      @review = current_user.reviews.build(review_params)
      @review.recipe = @recipe
      if @review.save
        redirect_to @recipe
       else
        render :"recipes/show"
     end
    end


      def update
        if @review.update(review_params)
          redirect_to @recipe
         else
          render :"recipes/show"
        end
      end
      




    private

    def set_recipe
        @recipe = Recipe.find(params[:recipe_id]) if params[:recipe_id]
    end

    def set_review
        @review = Review.find_by_id(params[:id])
    end

    def review_params
      params.require(:review).permit(:rating, :content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :redirect_if_not_logged_in, only: [:login, :create, :google_omniauth]

  
  
  
    def login

    end
  
    def create
      user = User.find_by_username(params[:username])
      
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to '/'
       else
        flash[:errors] = ["Invalid Username or Password!"]
        redirect_to login_path
      end
    end
  
  
    def logout
      session.clear
      redirect_to login_path
    end

   
    def google_omniauth
      user_info = request.env['omniauth.auth']["info"]
      user = User.find_or_create_from_google(user_info)

      if user
        session[:user_id] = user.id
        redirect_to user
       else
        flash[:errors] = user.errors.full_messages
        redirect_to login_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

    def new
     @user = User.new
    end


    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/'

         else
            render :new
        end
    end

    def show
     @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :zipcode)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_action :redirect_if_not_logged_in, only: [:home]

    def home
     render :home
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper


end

app/helpers/reviews_helper.rb
module ReviewsHelper


    def thumbs(int)
        int > 0 ? "👍" * int : "No reviews yet!"
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper


   
end

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
  <ul class="errors">
    <% record.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:errors] %>
<ul class="errors">
  <% flash[:errors].each do |error|%>
    <li><%=error%></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
<div class="topnav">
<% if logged_in? %>
  <%= link_to "Home Page", home_path %> &nbsp
  <%= link_to "Logout", logout_path, method: "delete" %> &nbsp
  <%= link_to "See All Recipes", recipes_path %> &nbsp &nbsp 
 </div>
<% else %>
  <%= link_to "Login", login_path %> &nbsp &nbsp 
  <%= link_to "Sign Up!", new_user_path %> &nbsp &nbsp  &nbsp
  <div class="google btn">
 <%= link_to "Sign In or Register with Google", "/auth/google_oauth2" %><br>
<% end %>
</div>

</nav>






  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodFusionApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 &nbsp
 <%= render 'layouts/nav' %>
 <%= render "layouts/flash" %>
 <%= yield %>
 &nbsp &nbsp 
 <br>
 <br>
 <footer class="branding">
      <a href="https://github.com/danyalshah3/Food_fusion_app" class="link" target="_blank">
      Github Repo </a><br>
    <a href="https://danyalm50.medium.com/rails-on-fire-249327041ca9"class="link" target="_blank">
      Blog Post</a><br>

    <a href= class="link" target="_blank">
      Video Demo</a><br>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
  <p><%= "#{pluralize(@recipe.errors.count, "error")} needs to be fixed:" %></p>
  <ul><% @recipe.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
    </ul>
    <% end %>
    
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :image %><br>
    <%= f.text_field:image_url %><br>
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients%><br>
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
    <%= f.label :minutes %><br>
    <%= f.number_field :minutes, in: (0..200) %><br>
    <br>
    <%= f.submit %><br>
  <% end %>

 

app/views/recipes/edit.html.erb
<div class="wrapper">
<h1>Edit <%= @recipe.name %> </h1>

<%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<br>
<h1>Welcome to the Recipes Library!</h1><br>
<br>

<div class="search">
<%= form_tag recipes_path, method: :get do %>
  <%= label_tag :Search %>
  <%= text_field_tag :search, params["search"], placeholder: "Pizza"%>
  <%= select_tag :sort, raw("
  <option value='alphabetical'>Alphabetical</option>
  <option value='number_reviews'>Most Reviews</option>
  <option value='average_review'>Average Review</option>
") %>
  <%= submit_tag "Search a Recipe!" %>
  <% end %>
  </div><br>
  <br>

  
  
  <div class="wrapper">
  <ul>
  <% @recipes.each do |recipe| %>
    <h2><li><%= link_to recipe.name, recipe %></li></h2>
    <% end %>
    </ul>
    </div>
    
    
    <button class="btn btn-primary"><%= link_to "Create A Recipe", new_recipe_path %></button>
    

app/views/recipes/new.html.erb
<div class="wrapper">
<h1> Add a recipe </h1>

<%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<div class="wrapper">
<h2> Recipe Details </h2>
<h3>Name: <%= @recipe.name %></h3>
<img src="<%= @recipe.image_url%>"alt="<%=@recipe.name%>'s Image"/>
<h3>Ingredients: <%= @recipe.ingredients %></h3>
<h3>Description: <%= @recipe.description %></h3>
<h3>Minutes_to_complete: <%= @recipe.minutes %></h5>
<p>Average reviews: <%= thumbs(@recipe.average_review) %><br>
<br>
</div>

<div>

<%= button_to "Edit #{@recipe.name}", edit_recipe_path(@recipe), method: :get%>
<%= button_to "Remove #{@recipe.name}", recipe_path(@recipe), method: :delete %>
</div>


<div class="wrapper">
<%= form_for [@recipe, @review] do |f| %>
    <%= render partial: "layouts/errors", locals: {record: @review} %><br>
    <%= f.label :rating %><br>
    <%= f.number_field :rating, min: 1, max: 5 %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.submit %><br>
  <% end %>
  </div>

<div>
  <%= render @recipe.reviews %>
 
  </div>

app/views/reviews/_review.html.erb
<div class="review">
<p><%= review.user.username %>: <%= thumbs(review.rating) %></p>
<p><%= review.content %></p>
</div>

app/views/users/new.html.erb
<h1>Hello World!</h1>
<h1>Welcome to Food-Fusion!</h1>
<div class="container">
  <%= form_for @user do |f| %>
  <%= render partial: "layouts/errors", locals: {record: @user} %>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.label :zipcode %><br>
    <%= f.number_field :zipcode, in: 10001..99999 %><br>
    <%= f.submit "Sign Up!" %><br>
  <% end %>
</div>



   
      

app/views/users/show.html.erb
<h1><Welcome %= @user.username %></h1>
<h3>Email: <%= @user.email %></h3>

app/views/welcome/home.html.erb
<h1>Welcome <%= logged_in? ? current_user.username : "to Food-Fusion" %> </h1>